on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Create/update release PR
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node

      # The logic below handles npm publication.  Each step is conditional on a
      # release having been created by someone merging the release PR.
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      #- run: npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      #  if: ${{ steps.release.outputs.release_created }}
      - run: npm pack
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/upload-release-asset@v1
        env:
          RELEASE_VERSION: ${{ steps.release.outputs.major }}-${{ steps.release.outputs.minor }}-${{ steps.release.outputs.patch }}.tgz
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          path: karma-local-wd-launcher-${{ env.RELEASE_VERSION }}.tgz
          asset_name: karma-local-wd-launcher-${{ env.RELEASE_VERSION }}.tgz
          asset_content_type: application/gzip
        if: ${{ steps.release.outputs.release_created }}
